

eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8761/eureka
server:
  port: 8000
spring:
  application:
    name: admin
  boot:
    admin:
      routes:
          endpoints: env,metrics,dump,jolokia,info,configprops,trace,logfile,refresh,flyway,liquibase,heapdump,loggers,auditevents,hystrix.stream
      turbine:
#        clusters: default
        location: admin
turbine:
  aggregator:
    cluster-config: default
  app-config: product
  clusterNameExpression: new String("default")